### PR TITLE
[CLOUD-3649] generating driver configuration according to DRIVERS env…

### PR DESCRIPTION
**Pull request by istudens**
…ironment variable

https://issues.redhat.com/browse/CLOUD-3649

### CODE REVIEW

**Comment by jfdenise** [comment]
@istudens , could you add bat tests and also backport this to the 0.18.x branch? Thank-you.

**Review by yersan — COMMENTED** [review]
Changes look good to me, I tested them manually and haven't found issues. Bats tests help with the maintenance and as documentation, so, necessary to have them in place.

**Comment by jfdenise** [comment]
@istudens , The backport is there:https://github.com/wildfly/wildfly-cekit-modules/pull/233
We will not wait for bats test @yersan is adding behave tests in the image repos.

**Comment by jfdenise** [comment]
@istudens , I cherry-picked your change and opened https://github.com/wildfly/wildfly-cekit-modules/pull/234, needed to be able to run CI. I am closing this one.

**Comment by istudens** [comment]
Ok, I will backport this to 0.18.0.

**Comment by jfdenise** [comment]
@istudens , the backport PR is already opened:https://github.com/wildfly/wildfly-cekit-modules/pull/233

**Comment by istudens** [comment]
@jfdenise ok, thanks

**Pull request closed without merging**
