### PR TITLE
Fix for #393, jboss.tx.node.id has no default value

### PR DESCRIPTION
**Pull request by jfdenise**

### CODE REVIEW

**Comment by jfdenise** [comment]
@rhusar if you could review, thank-you.

**Comment by rhusar** [comment]
> in case the server is launched without setting the system property.

Could you outline what are the situation where this is not actually set? I was under impression that all the launch scripts always explicitly set it?

**Comment by jfdenise** [comment]
@rhusar , in case openshift-launch.sh is not called to start the server (do a direct call to standalone.sh), then the env variable is not set. We can have such case (for example when using the wildfly:dev goal with the cloud feature-pack).

**Comment by rhusar** [comment]
> @rhusar , in case openshift-launch.sh is not called to start the server (do a direct call to standalone.sh), then the env variable is not set. We can have such case (for example when using the wildfly:dev goal with the cloud feature-pack).

I see, makes sense.

**Review by rhusar — APPROVED** [review]
LGTM 👍🏼

**Comment by jfdenise** [comment]
@rhusar , the failure is due to https://github.com/wildfly/wildfly-s2i/blob/main/wildfly-builder-image/tests/features/basic.feature#L594 that checks the server config and deans't expect a default value. It will have to be fixed.
BTW, Could you update https://github.com/wildfly/wildfly-cekit-modules/pull/391 to add the default value? Thank-you.

**Comment by rhusar** [comment]
> @rhusar , the failure is due to https://github.com/wildfly/wildfly-s2i/blob/main/wildfly-builder-image/tests/features/basic.feature#L594 that checks the server config and deans't expect a default value. It will have to be fixed. BTW, Could you update #391 to add the default value? Thank-you.

PR updated, thanks.

**Pull request merged**
