### PR TITLE
CLOUD-4174 Session affinity information is attached to the session ID but never used

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/CLOUD-4174

### CODE REVIEW

**Comment by jfdenise** [comment]
@rhusar , could you resync your branch, a bug has been fixed in CI. 
This fix applies to WildFly 29.x. Right?
What about EAP 7.4 and 8.0? Could we have a JBEAP issue created for these versions (cloud-galleon-pack as component for EAP 8, and Openshift for EAP 7.4).

**Comment by rhusar** [comment]
> @rhusar , could you resync your branch, a bug has been fixed in CI.

Done, CI is passing now.

> This fix applies to WildFly 29.x. Right?

Yes.

>  What about EAP 7.4 and 8.0? Could we have a JBEAP issue created for these versions (cloud-galleon-pack as component for EAP 8, and Openshift for EAP 7.4).

Opened https://issues.redhat.com/browse/JBEAP-25437 and https://github.com/wildfly/wildfly-cekit-modules/pull/392

Thanks @jfdenise !

**Comment by pferraro** [comment]
@jfdenise @jmesnil Can someone review this?

**Review by jfdenise — APPROVED** [review]

**Comment by jfdenise** [comment]
@pferraro , sorry for the slow review... I just approved it, will release a new cloud feature-pack with this change ASAP.

**Comment by jfdenise** [comment]
FYI: Latest cloud feature-pack contains the fix: https://github.com/wildfly-extras/wildfly-cloud-galleon-pack/releases/tag/4.0.3.Final

**Pull request merged**
