### PR TITLE
CLOUD-4211 Cloud clustering profiles should configure a distributed cache instead of a replicated one

### PR DESCRIPTION
**Pull request by rhusar**
Currently, our cloud tooling configures clustering in the cloud using a replicated cache mode which is suboptimal as it does not scale. Such cache mode does not scale and is not suited for applications in the cloud that are supposed to be scalable. In this mode Infinispan replicates all entries in the cache to all nodes in the cluster. It doesn't scale, as adding new nodes does not enlarge the cluster capacity. Moreover, we should relax the isolation level to READ_COMMITTED (from REPEATABLE_READ) and transaction mode to NONE (from BATCH).

Resolve
https://issues.redhat.com/browse/CLOUD-4211

### CODE REVIEW

**Comment by jfdenise** [comment]
@rhusar , do we really need to add the web dist cache? That is the default in the ha wildfly configuration: https://github.com/wildfly/wildfly/blob/main/ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/web-clustering/layer-spec.xml#L20 and https://github.com/wildfly/wildfly/blob/main/ee-feature-pack/galleon-shared/src/main/resources/feature_groups/infinispan-dist-web.xml#L10
Could we just remove all this adjustment?

**Review by jfdenise — APPROVED** [review]

**Review by pferraro — APPROVED** [review]

**Comment by jfdenise** [comment]
@rhusar , merged. Thank-you. The wildfy-cloud-galleon-pack 7.0.1.Final will to contain this fix.

**Comment by jfdenise** [comment]
@rhusar , FYI:https://github.com/wildfly-extras/wildfly-cloud-galleon-pack/releases/tag/7.0.1.Final

**Comment by rhusar** [comment]
Excellent, thanks! Will test.

**Comment by rhusar** [comment]
> @rhusar , do we really need to add the web dist cache? That is the default in the ha wildfly configuration: https://github.com/wildfly/wildfly/blob/main/ee-feature-pack/galleon-shared/src/main/resources/layers/standalone/web-clustering/layer-spec.xml#L20 and https://github.com/wildfly/wildfly/blob/main/ee-feature-pack/galleon-shared/src/main/resources/feature_groups/infinispan-dist-web.xml#L10 Could we just remove all this adjustment?

I forgot to reply to this one – but long story short, we wanted to change the configuration and finally rename the caches to something more reasonable.

**Pull request merged**
