### PR TITLE
[CLOUD-3941] - Logger configurations in OCP

### PR DESCRIPTION
**Pull request by msmagnanijr**
See:  https://issues.redhat.com/browse/CLOUD-3941

Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>

### CODE REVIEW

**Comment by msmagnanijr** [comment]
WIP

**Comment by msmagnanijr** [comment]
@luck3y when you can please take a look and tell me if it makes sense. in the meantime, I'm going to work on the tests.

**Comment by msmagnanijr** [comment]
@luck3y not sure if you had a chance to take a look at this.    @spolti If you can take a look as well.

**Comment by luck3y** [comment]
@msmagnanijr if you rebase this with master the tests should run. I haven't had time to look at it yet, but I will.

**Pull request closed without merging**
