### PR TITLE
Fix for #340, embedded-activemq Galleon layer needs adjustment for openshift

### PR DESCRIPTION
**Pull request by jfdenise**
Fix issue #340

### CODE REVIEW

**Comment by jmesnil** [comment]
@ehsavoie, could you please review?

I don't understand why the embedded-activemq layer that should only deal with in-vm connections needs a RemoteConnectionFactory in its spec....

**Comment by jfdenise** [comment]
@jmesnil , the s2i V1 embedded broker support is adding a remote connection factory and http acceptor. This is the openshift config: https://gist.github.com/jfdenise/ebacd097d914a125944543bcbacd9a4f

**Comment by ehsavoie** [comment]
@jfdenise @jmesnil since remote access would create a whole bunch of issues without a proper broker cluster (in which case you should use a remote broker cluster) I would remove that connection factory

**Comment by jfdenise** [comment]
@ehsavoie one use case that seems important is being able to remotely access a server in which an embedded broker is running. So acting as a remote broker. I understand that it couldn't be scaled.

**Comment by ehsavoie** [comment]
:+1: Whatever we decide, the current PR doesn't bring in nor fix any issue related to the use-case so we can still merge it and see how we want to address the use-cases in another one.

**Review by ehsavoie — APPROVED** [review]

**Pull request merged**
